
import java.util.Random;

// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		double times = Double.parseDouble(args[0]);
		int counter, counterG = 0;// counterG= counter Greater than 0.5, counter= count the num less then 0.5
		for (int i = 0; i < times; i++) {
			double number = Math.random();
			// System.out.println(number);
			if (number >= 0.5) {
				counterG++;
			}
		}
		counter = (int) times - counterG;
		System.out.println("> 0.5: " + counter);
		System.out.println("<= 0.5: " + counterG);
		System.out.println("Ratio: " + (times - counterG) / counterG);
	}

}
